package PruebaUDP;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;

public class ServidorUDP {
    public static void main(String[] args) {
        try {
            DatagramSocket socket = new DatagramSocket(41500);

            while (true) {
                System.out.println("Creaci贸n del array de bytes");
                byte[] buffer = new byte[64];

                System.out.println("Creaci贸n del datagrama");
                DatagramPacket packet = new DatagramPacket(buffer, buffer.length);
                System.out.println("A la espera de recibir el datagrama");
                socket.receive(packet);

                System.out.println("Leemos el mensaje");
                String mensaje = new String(packet.getData());
                System.out.println("Mensaje enviado por el cliente: " + mensaje.trim());
            }

        } catch (SocketException e) {
            System.err.println("Error en la creaci贸n del socket");
            throw new RuntimeException(e);
        } catch (IOException e) {
            System.err.println("Error en la recuperaci贸n del paquete");
            throw new RuntimeException(e);
        }
    }
}
